# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php
sudo: false

cache:
  yarn: true
  directories:
   - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.3
      dist: precise
      script: yarn build-php-production
    - php: 5.6
    - php: 7.0
    - php: 7.2
    - php: 7.3
      script: yarn php:compatibility **/*.php

# Git clone depth
# By default Travis CI clones repositories to a depth of 50 commits
git:
  depth: 1

before_install:
  - composer self-update

install:
  - nvm install
  - npm i -g yarn && yarn && yarn build-php

notifications:
  email: false
  slack:
    rooms:
      secure: "Y/csKsxEnqYmKY0FtEydYwKuhBoKURKE64Vnz6JEaxFSnfJyw2YASSQxueN6FlliH+vRZBaD/xgJGmq6sccM9wBij5cRimGu9NT2HsbJwEGZGn81mK6S1KbZSrV4UgJ/ks0m5gVL6eeo7ws3RwbIaM+LTB7cj4JuhGL2Q32fU5dp9mjbvvzziGFxX3z/86NE9Co1H++XNTTLC2XVkZP/Mvvr4ffa89HBhwilvygK/DBygzzO4o+VwwGPbSBZ6sdq8nW4REyfde92xdaUhWHij8l0y9v1e4i31RmqG+0fbBiVgOgpZr3piO9E9w5MVY4bYr+C6MhslqKtxGnBogqlszfCdn7hvUWxOF4ccrLyej5TFx3zSrM5/Jq2Dv+w0IdqP45ssyL7XQ4oBsm3ABGtiHiyT3bbjBoxp16bSHLAfvxPjQZVfaIcqJ+setg7yMTLl1N4lzOHKlpqVJM1J5261u6Zqcwi/XXtQyriP3eGBSWyz8Ud6d2RfCB7pTmE7DPHRovea5fzpdTK+aD88hQSCPOofgrxOz5emVWpvvyKxgUyhDvEQ4fzjRhIrUDCb5tDsJ0QXovQ7prALyqGg1QpMDwYfhn+a0aH71PQ6f9llM9MHJedptlBQmDDHrnr6ya1WU55y3dyxH3lsZTmd+gGO4aLHwPKCQOrSYOpOi9i+Xs="
    on_success: never
    on_failure: always
