# This Github Action is temporary, to run the development version of PHPCompatibility to test for PHP 8 issues.
#
# Once we're getting that by default (likely due to an upgrade of automattic/jetpack-codesniffer to pull a version of phpcompatibility/phpcompatibility-wp that pulls phpcompatibility/php-compatibility 10.0+),
# this action and .github/files/phpcompatibility-dev-phpcs.xml should be deleted.

name: PHP Compatibility Dev

on: pull_request

jobs:
  phpcompatibility:
    name: dev branch for PHP 8.0
    runs-on: ubuntu-latest
    timeout-minutes: 3 # Successful runs seem to take ~1 minute

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer
          extensions: mysql, imagick
          coverage: none

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Use composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Tool versions
        run: |
          which php
          php --version
          which composer
          composer --version
          which jq
          jq --version

      - name: Install dependencies
        run: composer install

      - name: Upgrade PHPCompatibility
        run: |
          if [[ -e vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniffs/ControlStructures/NewNonCapturingCatchSniff.php ]]; then
            echo "::error file=.github/workflows/phpcompatibility-dev.yml,line=4,col=1::It looks like PHPCompatibility is already at version 10.0, making this Github Action obsolete. Please remove it."
            exit 1
          fi
          composer remove --dev automattic/jetpack-standards
          composer require --dev phpcompatibility/php-compatibility=dev-develop

      - name: Run phpcs for PHPCompatibility
        run: |
          vendor/bin/phpcs -p -s --report=emacs --standard=.github/files/phpcompatibility-dev-phpcs.xml
