name: PHP compatibility tests

on: pull_request

jobs:
  compatibility:
    name: PHP (${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 3  # Successful runs seem to take ~1 minute

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '5.6', '7.0', '7.2', '7.3', '7.4', '8.0' ]
        experimental: [ false ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Use composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Tool versions
        run: |
          which php
          php --version
          which composer
          composer --version
          node --version
          which yarn
          yarn --version
          which jq
          jq --version

      - name: Install dependencies
        run: |
          # Install repo dependencies
          yarn && yarn build-php

      - name: Run the unit tests
        run: |
          yarn php:compatibility **/*.php
